# Generated by Django 5.1.5 on 2025-02-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
        migrations.AlterField(
            model_name='level',
            name='code',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
