# Generated by Django 5.1.5 on 2025-02-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_subject_code_alter_level_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
    ]
