# Generated by Django 5.1.5 on 2025-02-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_question_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='order_number',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
