# Generated by Django 5.1.5 on 2025-02-07 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_question_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='order_number',
        ),
    ]
