# Generated by Django 5.1.5 on 2025-02-07 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='lastname',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='app.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userresult',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userresult',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_results', to='app.user'),
            preserve_default=False,
        ),
    ]
